### ISSUE TITLE
AltAutoMode [PH] - H-positions list Bug

### ISSUE THREAD

**Issue by abc098P** [IllusionMods/KeelPlugins#35]
This plugin causes a problem in game h scene that all of "map specific positions" buttons are appeared in h-positions list regardless of the current selected map.

**Comment by AgiShark** [comment]
It's not a bug, it's one of the unstated features.
The plugin code contains a prefix that unlocks H-positions regardless of maps and game progress.

**Comment by ManlyMarco** [comment]
So is this fine or is this an issue? I don't play PH so I don't really have a reference point.

**Comment by AgiShark** [comment]
I believe it's intentional that H-positions unlock regardless of map and game progression.
The plugin author has never published this plugin on a sharing channel.
So, It's most likely created for the personal use of the plugin author, not for random users.
For the plugin author, this is not an issue.
But the unlock feature is not explicitly stated.
And random users cannot turn on/off only the unlock feature in the game.
So, I think introducing an option to turn on/off the feature in the plugin/mod setting can be an improvement for users. 
Or separate it as a small standalone plugin.
I mean, **only** if it's not too much trouble for you.

**Comment by ManlyMarco** [comment]
Here you go.

**Comment by AgiShark** [comment]
@abc098P Just in case you don't know how to compile.
[AltAutoMode.PH_2022.08.07.zip](https://github.com/IllusionMods/KeelPlugins/files/9280508/AltAutoMode.PH_2022.08.07.zip)

**Comment by abc098P** [comment]
@ManlyMarco @AgiShark
It works fine. Thank you for check and the improvement.
